### PR TITLE
Remove fonts from Submodules and use system fonts for 1.0.0 release

### PR DESCRIPTION
**Pull request by msmollin**
### Overview
This change removes the stylesheet bundled fonts and relies upon system font loading for the 1.0.0 release until fixes can be merged from Tangram-es to properly address #286

### CODE REVIEW

**Comment by tallytalwar** [comment]
Since this change will affect the look of the text in the bundled scenes, we decided that its probably best for @nvkelso to have a look at the rendered scene with the change.

Since @matteblair is visiting SF, he will be confirming with our carto team and coordinating the change. Once I get a 👍 from the carto team will merge this.

**Comment by msmollin** [comment]
@tallytalwar OK I listed a more detailed explanation in #286 if you want to add anymore details / provide corrections.

**Comment by matteblair** [comment]
Ok I've checked in with the carto team and everyone agrees that it's better to ship with only the iOS system fonts at launch than to ship with garbled text.

@msmollin Once you've confirmed that this prevents the issue from surfacing in extended use, I think we're good to merge this.

**Comment by msmollin** [comment]
Roger and thanks for talking to them. I have all the devices I replicated this on at home so I'll exercise this tomorrow and report back.

**Comment by tallytalwar** [comment]
I checked this on 10.0.x iphone and 10.3.1 iphone we have at work today. Looks good.

**Comment by msmollin** [comment]
Checked this on iOS 9.3.5 iPad Mini 1 by starting in Baghdad, then going to NYC central park, then Seoul, then downtown Bejing, and then Moscow, all of which I got to load different glyph styles. Upon going back to NYC there was still no issues. The same series of events also didn't showcase anything on my 10.2.1 iPad Air, so this seems to have resolved the issue.

**Pull request merged**
