### PR TITLE
Update Readme for installation instructions

### LINKED ISSUE #21: Add README

### PR DESCRIPTION
**Pull request by msmollin**
Fixes #21

### CODE REVIEW

**Comment by ecgreb** [comment]
@tallytalwar can you test drive these setup instructions and report back if you run into any issues.

Looks like the main challenges might be around getting Cocoapods installed correctly for your specific version of xcode/swift.

**Comment by karimnaaji** [comment]
Instructions looks good!

One issue I had after running `pod install`:

screen shot 2016-10-24 at 2 29 58 pm

When looking at the provisioning Profile
screen shot 2016-10-24 at 2 31 02 pm
:

What are the steps to get it to build in that case?

**Comment by msmollin** [comment]
Ah yeah should probably put a note in there if you're building for device (which is required until we get simulator support working in tangram) that you have to change the bundle identifier to something you can provision for, and then go through all the steps of making a provisioning profile for it.

**Comment by karimnaaji** [comment]
I see, those steps/instructions would be a good addition to build for device.

We already added simulator support in Tangram from https://github.com/tangrams/tangram-es/pull/1003, we only need to move forward and update the binary framework.

**Comment by tallytalwar** [comment]
BTW, @karimnaaji got simulator added to ios-framework.

**Comment by msmollin** [comment]
@karimnaaji / @tallytalwar added a note about the code signing issue in the readme. 

We can update the readme again once we're ready to merge in simulator support from tangram.

**Comment by karimnaaji** [comment]
Looks good.

**Pull request merged**
